fh/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from ratelimitbackend import admin
from django.views.generic.base import RedirectView
from users.views import PasswordChangeRedirectView
from users.forms import ValidatingPasswordChangeForm
from fh.views import tags

admin.autodiscover()

admin.site.site_header = 'FamilyHelper administration'

urlpatterns = [
    url(r'^autocomplete/', include('autocomplete_light.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', auth_views.login, name='login'),
    url(r'^accounts/logout', auth_views.logout, {'next_page': '/'}),
    url(r'tags/$', tags, name='tags_all'),
    url(r'tags/(?P<query>.+)/$', tags, name='tags_query'),
    url(r'^finances/', include('finances.urls', namespace="finances")),
    url(r'^tasks/', include('tasks.urls', namespace="tasks")),
    url(r'^tv/', include('tv.urls', namespace="tv")),
    url(r'^analytics/', include('analytics.urls', namespace="analytics")),
    url(r'users/profile/password$', auth_views.password_change, {
        'template_name': 'users/password_change_form.html', 'password_change_form': ValidatingPasswordChangeForm},
        name='password_change'),
    url(r'users/profile/password/done$', PasswordChangeRedirectView.as_view(), name='password_change_done'),
    url(r'^users/', include('users.urls', namespace="users")),
    url(r'^avatar/', include('avatar.urls')),
    url(r'^$', RedirectView.as_view(pattern_name='finances:payments_list', permanent=True), name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

finances/urls.py
from django.contrib.auth.decorators import permission_required
from django.conf.urls import url

import finances.views as views

urlpatterns = [
    url(r'payment/add/$', permission_required('finances.add_payment')(views.PaymentCreate.as_view()),
        name='payment_add'),
    url(r'payment/$', permission_required('finances.add_payment')(views.PaymentList.as_view()), name='payments_list'),
    url(r'payment/(?P<pk>[0-9]+)/$', permission_required('finances.change_payment')(views.PaymentUpdate.as_view()),
        name='payment_update'),
    url(r'payment/(?P<pk>[0-9]+)/delete$',
        permission_required('finances.delete_payment')(views.PaymentDelete.as_view()), name='payment_delete'),
]

finances/forms.py
from autocomplete_light.contrib.taggit_field import TaggitField, TaggitWidget
import autocomplete_light
from django import forms
from datetime import date
from django.utils import timezone
from taggit.models import Tag
from django.forms import Form
from fh.forms import FormInitialDataMixin
from users.models import User


class PaymentForm(autocomplete_light.ModelForm):
    """
    Payment add/edit form
    """
    tags = TaggitField(widget=TaggitWidget('TagAutocomplete'))


class PaymentsFilterForm(Form, FormInitialDataMixin):
    """
    Payments list filter form
    """

    def __init__(self, *args, **kwargs):

        super(PaymentsFilterForm, self).__init__(*args, **kwargs)

        self.dates = {
            'tomorrow': date.fromordinal(timezone.now().toordinal() + 1),
            'today': date.today(),
            'yesterday': date.fromordinal(timezone.now().toordinal() - 1),
            'week': date.fromordinal(timezone.now().toordinal() - 7),
            'month': date.fromordinal(timezone.now().toordinal() - 31),
            'year': date.fromordinal(timezone.now().toordinal() - 365),
        }
        self.tags = Tag.objects.all().order_by('name')

        self.fields['begin'] = forms.DateField(
            label='From',
            required=True,
            input_formats=('%Y-%m-%d',),
            widget=forms.TextInput(attrs={'placeholder': self.dates['week'], 'class': 'datepicker'}),
            initial=self.dates['year']
        )
        self.fields['end'] = forms.DateField(
            label='To',
            required=True,
            input_formats=('%Y-%m-%d',),
            widget=forms.TextInput(attrs={'placeholder': self.dates['tomorrow'], 'class': 'datepicker'}),
            initial=self.dates['tomorrow']
        )
        self.fields['period'] = forms.ChoiceField(
            label='Period',
            required=False,
            choices=(
                ('', '---------'),
                ('%s_%s' % (self.dates['today'], self.dates['tomorrow']), 'Today'),
                ('%s_%s' % (self.dates['yesterday'], self.dates['today']), 'Yesterday'),
                ('%s_%s' % (self.dates['week'], self.dates['tomorrow']), 'Last week'),
                ('%s_%s' % (self.dates['month'], self.dates['tomorrow']), 'Last month'),
                ('%s_%s' % (self.dates['year'], self.dates['tomorrow']), 'Last year'),
            ),
            initial='%s_%s' % (self.dates['year'], self.dates['tomorrow'])
        )
        self.fields['include_tags'] = forms.ModelMultipleChoiceField(
            label='Tags <small><i class="fa fa-plus-circle"></i></small>',
            required=False,
            queryset=self.tags,
            widget=forms.SelectMultiple(attrs={"data-live-search": "true", "data-size": 10})
        )
        self.fields['exclude_tags'] = forms.ModelMultipleChoiceField(
            label='Tags  <small><i class="fa fa-minus-circle"></i></small>',
            required=False,
            queryset=self.tags,
            widget=forms.SelectMultiple(attrs={"data-live-search": "true", "data-size": 10})
        )
        self.fields['user'] = forms.ModelChoiceField(
            required=False,
            empty_label="---------",
            queryset=User.objects.all()
        )
        self.fields['is_debt'] = forms.ChoiceField(
            label='Is debt',
            required=False,
            choices=(
                ('', '---------'), (1, 'Yes'), (0, 'No')
            )
        )
        self.fields['is_incoming'] = forms.ChoiceField(
            label='Is incoming',
            required=False,
            choices=(
                ('', '---------'), (1, 'Yes'), (0, 'No')
            )
        )

    def clean(self):
        data = super(PaymentsFilterForm, self).clean()
        begin = data.get("begin")
        end = data.get("end")
        is_incoming = self.cleaned_data['is_incoming']
        is_debt = self.cleaned_data['is_debt']
        self.cleaned_data['is_incoming'] = bool(int(data.get("is_incoming"))) if is_incoming else None
        self.cleaned_data['is_debt'] = bool(int(data.get("is_debt"))) if is_debt else None
        self.cleaned_data['include_tags'] = data.get("include_tags") if data.get("include_tags") else None
        self.cleaned_data.pop("period", None)

        if begin and end:
            if begin > end or abs((end - begin).days) > 366 * 2:
                msg = "Period self.dates incorrect."
                self.add_error('begin', msg)
                self.add_error('end', msg)

finances/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView
from django.core.urlresolvers import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from .models import Payment
from .forms import PaymentsFilterForm
from fh.forms import ModelFormWidgetMixin
from django import forms


class PaymentFormViewMixin:
    """
    Payment form mixin
    """
    model = Payment
    fields = ['tags', 'amount', 'date', 'comment', 'is_debt', 'is_incoming']
    widgets = {
        'date': forms.DateTimeInput(attrs={'placeholder': '2015-11-24 14:59:19', 'class': 'datetimepicker'}),
        'comment': forms.Textarea(attrs={'rows': 3})
    }


class PaymentCreate(SuccessMessageMixin, PaymentFormViewMixin, ModelFormWidgetMixin, CreateView):
    """
    Payment create view
    """
    success_message = "Payment was created successfully"
    success_url = reverse_lazy('finances:payments_list')


class PaymentUpdate(SuccessMessageMixin, PaymentFormViewMixin, ModelFormWidgetMixin, UpdateView):
    """
    Payment update view
    """
    success_message = "Payment was updated successfully"
    success_url = reverse_lazy('finances:payments_list')


class PaymentList(ListView):
    """
    Payments list view
    """
    THEAD = (
        {'title': 'tags'},
        {'title': 'amount',  'class': 'td-md text-right',  'sort': 'amount'},
        {'title': 'date', 'class': 'td-md hidden-xs', 'sort': 'date'},
        {'title': 'in', 'class': 'td-xs text-center hidden-xs', 'sort': 'is_incoming'},
        {'title': 'debt', 'class': 'td-sm text-center hidden-xs', 'sort': 'is_debt'},
        {'title': 'user', 'class': 'td-sm text-center', 'sort': 'created_by'},
    )
    model = Payment
    paginate_by = 20

    def get_context_data(self, **kwargs):
        context = super(PaymentList, self).get_context_data(**kwargs)
        form = PaymentsFilterForm(self.request.GET if self.request.GET.get('filter', False) else None)
        data = form.cleaned_data if form.is_valid() else form.get_initial_data(exclude=('period',))
        context['summary'] = Payment.objects.summary(**data)
        context['thead'] = self.THEAD
        context['form'] = form
        context['filter'] = data

        return context

    def get_queryset(self):
        form = PaymentsFilterForm(self.request.GET if self.request.GET.get('filter', False) else None)
        sort = self.request.GET.get('sort')
        order = self.request.GET.get('order')
        data = form.cleaned_data if form.is_valid() else form.get_initial_data(exclude=('period',))
        data.pop("period", None)

        return Payment.objects.filtered(sort=sort, order=order, **data).select_related('created_by')


class PaymentDelete(DeleteView):
    """
    Payment delete view
    """
    model = Payment
    success_url = reverse_lazy('finances:payments_list')
    template_name = "partials/confirm_delete.html"
    success_message = "Payment was deleted successfully"

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(PaymentDelete, self).delete(request, *args, **kwargs)

finances/templates/finances/layout.html
{% extends 'layout.html' %}
{% load staticfiles %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'bootstrap-tagsinput/src/bootstrap-tagsinput.css' %}">
    <link rel="stylesheet" href="{% static 'finances/css/finances.css' %}">
{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script src="{% static 'bootstrap-tagsinput/src/bootstrap-tagsinput.js' %}"></script>
    <script src="{% static 'finances/js/finances.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="box box-default">
        <div class="box-body">
            {% block finances_content %}{{ block.super }}{% endblock %}
        </div>
    </div>
{% endblock %}

finances/templates/finances/payment_filter.html
{% load crispy_forms_tags %}

{% include 'partials/box_widget_begin.html' with header='Filter' id='finances-filter-form-widget' %}
<form action="{% url action %}" method="get">
    {{ form|crispy }}

    <button type="submit" name="filter" value="1" class="btn btn-primary  margin-right-sm">
        <i class="fa fa-filter"></i><span class="margin-left-sm">Filter</span>
    </button>
    <a href="{% url cancel %}" class="btn btn-default">
        <i class="fa fa-ban"></i><span class="margin-left-sm">Cancel</span>
    </a>

</form>
{% include 'partials/box_widget_end.html' %}

finances/templates/finances/payment_form.html
{% extends 'finances/layout.html' %}
{% load avatar %}
{% load humanize %}
{% load crispy_forms_tags %}

{% block finances_content %}

    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form|crispy }}

        {% include 'partials/entry_info.html' with entry=payment %}

        {% include 'partials/entry_buttons.html' with entry=payment title='payment' list_url='finances:payments_list' delete_url='finances:payment_delete' delete_permission=perms.finances.delete_payment %}
    </form>

{% endblock %}

finances/templates/finances/payment_list.html
{% extends 'finances/layout.html' %}
{% load humanize %}
{% load avatar %}

{% block finances_content %}

    {% include 'finances/payment_summary.html' with summary=summary link='finances:payments_list' filter=filter add=True %}

    <div class="row">
        <div class="col-md-3 col-md-push-9">

            <!------------------- FILTERS ------------------->
            {% include 'finances/payment_filter.html' with form=form action='finances:payments_list' cancel='finances:payments_list' %}
        </div>

        <!------------------- LIST ------------------->
        <div class="col-md-9 col-md-pull-3">

            {% if object_list|length %}

                <table class="table table-striped table-hover">

                    {% include 'partials/thead.html' with thead=thead link='finances:payments_list' %}

                    <tbody>
                    {% for payment in object_list %}
                        <tr class="{{ payment.is_debt|yesno:"danger," }} {{ payment.is_incoming|yesno:"success," }}">
                            <td>
                                {% for tag in payment.tags.all %}
                                    <a href="{% url 'finances:payments_list' %}?include_tags={{ tag.id }}&filter=1&begin={{ filter.begin|date:'Y-m-d' }}&end={{ filter.end|date:'Y-m-d' }}"
                                       class="btn btn-info btn-xs tag-link">{{ tag }}</a>&nbsp;
                                {% endfor %}
                            </td>
                            <td class="text-right {{ payment.is_incoming|yesno:"text-success," }}">
                                {% if payment.comment %}
                                    <span class="bottom-dotted cursor-help" data-html="true" data-toggle="tooltip" data-placement="top" title="{{ payment.comment|safe }}">
                                        {{ payment.amount|intcomma }}
                                    </span>&nbsp;<small><i class="fa fa-info-circle"></i></small>
                                {% else %}
                                    {{ payment.amount|intcomma }}
                                {% endif %}

                            </td>
                            <td class="hidden-xs">{{ payment.date|naturalday }} {{ payment.date|date:'H:i' }}</td>
                            <td class="text-center hidden-xs">
                                {% if payment.is_incoming %}<i class="fa fa-check text-success"></i>{% endif %}
                            </td>
                            <td class="text-center hidden-xs">
                                {% if payment.is_debt %}<i class="fa fa-check text-danger"></i>{% endif %}
                            </td>
                            <td class="text-center">
                                <a href="{% url 'finances:payments_list' %}?user={{ payment.created_by.id }}&filter=1&begin={{ filter.begin|date:'Y-m-d' }}&end={{ filter.end|date:'Y-m-d' }}">
                                    <img src="{% cached_avatar_url payment.created_by|default:'' 24 %}"
                                     title="{{ payment.created_by|default:"anonym" }}" data-toggle="tooltip"
                                     data-placement="left"
                                     class="img-circle">
                                </a>
                            </td>
                            <td class="text-right">
                                <div class="dropdown">
                                    <button class="btn btn-{{ payment.is_incoming|yesno:"success,default" }} btn-sm dropdown-toggle" type="button"
                                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                        <i class="fa fa-cogs "></i>
                                        <span class="hidden-xs margin-left-sm">Actions <span class="caret"></span></span>
                                    </button>
                                    <ul class="dropdown-menu pull-right">
                                        {% if perms.finances.change_payment %}
                                            <li>
                                                <a href="{% url 'finances:payment_update' payment.id %}">
                                                    <i class="fa fa fa-pencil-square-o margin-right-sm"></i>Edit entry
                                                </a>
                                            </li>
                                        {% endif %}
                                        {% if perms.finances.delete_payment %}
                                            <li>
                                                <a href="{% url 'finances:payment_delete' payment.id %}"
                                                   class="text-success">
                                                    <i class="fa fa-trash margin-right-sm"></i>Delete entry
                                                </a>
                                            </li>
                                        {% endif %}
                                    </ul>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>

                {% if is_paginated %}{% load pager %}{% pager "finances:payments_list" %}{% endif %}

            {% else %}
                <div class="alert alert-warning">
                    <i class="fa fa-exclamation-circle"></i> Payments not found.
                </div>
            {% endif %}

        </div>
    </div>
{% endblock %}

finances/templates/finances/payment_summary.html
{% load humanize %}

<div class="row margin-bottom-lg">
    <div class="col-xs-9">
        <div class="btn-group" role="group">
            <a href="{% url link %}?is_incoming=0&filter=1&begin={{ filter.begin|date:'Y-m-d' }}&end={{ filter.end|date:'Y-m-d' }}"
               class="btn btn-xs btn-primary hidden-xs btn-flat">
                <i class="fa fa-minus margin-right-sm"></i>
                <span class="hidden-xs margin-right-sm">Out:</span>
                {{ summary.out|intcomma }}
            </a>
            <a href="{% url link %}?is_incoming=1&filter=1&begin={{ filter.begin|date:'Y-m-d' }}&end={{ filter.end|date:'Y-m-d' }}"
               class="btn btn-xs btn-info hidden-xs btn-flat">
                <i class="fa fa-plus margin-right-sm"></i>
                <span class="hidden-xs margin-right-sm">In:</span>
                {{ summary.in|intcomma }}
            </a>
            <a href="{% url link %}?is_debt=1&filter=1&begin={{ filter.begin|date:'Y-m-d' }}&end={{ filter.end|date:'Y-m-d' }}"
                   class="btn btn-xs btn-warning hidden-xs btn-flat">
                    <i class="fa fa-{% if summary.debt != 0 %}exclamation{% else %}check{% endif %} margin-right-sm"></i>
                    <span class="hidden-xs margin-right-sm">Debts:</span>
                    {{ summary.debt|intcomma }}
            </a>
            <a href="{% url link %}"
               class="btn btn-xs btn-{% if summary.total < 0 %}danger{% else %}success{% endif %} btn-flat">
                <i class="fa fa-{% if summary.total < 0 %}exclamation{% else %}check{% endif %} margin-right-sm"></i>
                <span class="hidden-xs margin-right-sm">Total:</span>
                {{ summary.total|intcomma }}
            </a>
        </div>
    </div>
    {% if add %}
        <div class="col-xs-3 text-right">
            <a href="{% url 'finances:payment_add' %}" class="btn btn-success btn-sm">
                <i class="fa fa-plus-circle"></i>
                <span class="hidden-xs margin-left-sm">Add payment</span>
            </a>
        </div>
    {% endif %}
</div>