fh/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from ratelimitbackend import admin
from django.views.generic.base import RedirectView
from users.views import PasswordChangeRedirectView
from users.forms import ValidatingPasswordChangeForm
from fh.views import tags

admin.autodiscover()

admin.site.site_header = 'FamilyHelper administration'

urlpatterns = [
    url(r'^autocomplete/', include('autocomplete_light.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', auth_views.login, name='login'),
    url(r'^accounts/logout', auth_views.logout, {'next_page': '/'}),
    url(r'tags/$', tags, name='tags_all'),
    url(r'tags/(?P<query>.+)/$', tags, name='tags_query'),
    url(r'^finances/', include('finances.urls', namespace="finances")),
    url(r'^tasks/', include('tasks.urls', namespace="tasks")),
    url(r'^tv/', include('tv.urls', namespace="tv")),
    url(r'^analytics/', include('analytics.urls', namespace="analytics")),
    url(r'users/profile/password$', auth_views.password_change, {
        'template_name': 'users/password_change_form.html', 'password_change_form': ValidatingPasswordChangeForm},
        name='password_change'),
    url(r'users/profile/password/done$', PasswordChangeRedirectView.as_view(), name='password_change_done'),
    url(r'^users/', include('users.urls', namespace="users")),
    url(r'^avatar/', include('avatar.urls')),
    url(r'^$', RedirectView.as_view(pattern_name='finances:payments_list', permanent=True), name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf.urls import url
import users.views as views


urlpatterns = [
    url(r'profile$', views.Profile.as_view(), name='profile'),
    url(r'profile/edit$', views.UserUpdate.as_view(), name='profile_edit'),
]

fh/models.py
from django.db import models
from users.models import User
from sitetree.models import TreeItemBase, TreeBase


class TagsMixin:
    """ Tags model mixin """

    def get_tags_as_string(self):
        """
        Return tags as formatted string
        :return: formatted string
        """
        return ', '.join([tag.name for tag in self.tags.all()])

    get_tags_as_string.short_description = 'Tags'


class CommonInfo(models.Model):
    """ CommonInfo abstract model """

    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True, editable=False)
    modified_at = models.DateTimeField(auto_now=True, null=True, blank=True, editable=False)
    created_by = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL,
                                   related_name="%(app_label)s_%(class)s_created_by")
    modified_by = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL, editable=False,
                                    related_name="%(app_label)s_%(class)s_modified_by")

    class Meta:
        abstract = True


class SiteTreeTree(TreeBase):
    """ FH tree model."""
    pass


class SiteTreeItem(TreeItemBase):
    """ FH tree item model."""

    icon = models.CharField(max_length=50, null=True, help_text='FontAwesome icon. Example: fa-user.')

fh/forms.py
from django.forms.models import modelform_factory


class FormInitialDataMixin:
    """
    Get initial data mixin
    """

    def get_initial_data(self, exclude=[]):
        return {key: field.initial for (key, field) in self.fields.items() if key not in exclude}


class ModelFormWidgetMixin(object):
    def get_form_class(self):
        return modelform_factory(self.model, fields=self.fields, widgets=self.widgets)

fh/views.py
from django.http import JsonResponse
from taggit.models import Tag


def tags(request, query=None):
    """
    JSON tags list
    :param request:
    :param query:
    :return: JsonResponse
    """
    items = Tag.objects
    if query:
        items = items.filter(name__contains=query.strip())
    data = [tag.name for tag in items.order_by('name').all()]
    return JsonResponse(data, safe=False)

fh/templates/partials/box_widget_begin.html
<div class="box box-{{ type|default:'default' }} box-solid">
    <div class="box-header">
        <h3 class="box-title">
            {{ header }}{% if smallHeader %}<small>{{ smallHeader }}</small>{% endif %}
        </h3>
        <div class="box-tools pull-right">
            <button class="btn btn-box-tool form-group-collapse" {% if id %}id="{{ id }}"{% endif %} data-widget="collapse">
                <i class="fa fa-minus"></i>
            </button>
        </div>
    </div>
    <div class="{{ class|default:'bg-gray-disabled color-palette' }} box-body">

fh/templates/partials/box_widget_end.html
</div></div>

fh/templates/partials/confirm_delete.html
{% extends 'layout.html' %}

{% block content %}
    <div class="box box-default">
        <div class="box-body">
            <form action="" method="post">
                {% csrf_token %}

                <button type="submit" class="btn btn-danger margin-right-md">
                    <i class="fa fa-trash"></i>
                    Are you sure you want to delete {{ object }}?
                </button>
                <button type="button" onclick="history.go(-1);return false;"
                        class="btn btn-default">
                    <i class="fa fa-ban"></i>
                    <span class="hidden-xs margin-left-sm">Cancel</span>
                </button>

            </form>
        </div>
    </div>
{% endblock %}

fh/templates/partials/entry_buttons.html
{% load avatar %}
{% load humanize %}

<button type="submit" class="btn btn-success margin-right-sm">
    <i class="fa fa-check-circle-o"></i><span class="margin-left-sm">Save {{ title }}</span>
</button>
<a href="{% url list_url %}" class="btn btn-default">
    <i class="fa fa-ban"></i><span class="hidden-xs margin-left-sm">Cancel</span>
</a>
{% if entry and delete_permission %}
    <a href="{% url delete_url entry.id %}" class="btn btn-danger pull-right">
        <i class="fa fa-trash"></i><span class="hidden-xs margin-left-sm">Delete {{ title }}</span>
    </a>
{% endif %}

fh/templates/partials/entry_info.html
{% load avatar %}
{% load humanize %}

{% if entry %}
    <div class="bg-gray color-palette alert">
        <img src="{% cached_avatar_url entry.created_by|default:'' 24 %}" class="img-circle margin-right-sm">
        Created at {{ entry.date|naturalday }} {{ entry.date|date:'H:i' }}
        by {{ entry.created_by|default:"anonym" }}
    </div>
{% endif %}

fh/templates/partials/header.html
{% load staticfiles %}
{% load avatar %}
{% load humanize %}

<header class="main-header">
    <!-- Logo -->
    <a href="{% url 'index' %}" class="logo">
      <span class="logo-mini">
          <img src="{% static 'img/favicon_24x24.png' %}" height="24" width="24">
      </span>
      <span class="logo-lg">
          <img id="fh-navbar-logo" src="{% static 'img/favicon_24x24.png' %}" height="24" width="24">
          <b>Family</b>Helper
      </span>
    </a>

    <nav class="navbar navbar-static-top" role="navigation">

        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>

        <div class="navbar-custom-menu">
            {% if user.is_authenticated %}
                <ul class="nav navbar-nav">

                    <!-- User Account -->
                    <li class="dropdown user user-menu">
                        <a href="{% url 'users:profile' %}" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="{% cached_avatar_url user 25 %}" class="user-image" alt="User avatar">
                            <span class="hidden-xs">{{ user }}</span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="user-header">
                                <img src="{% cached_avatar_url user 160 %}" class="img-circle" alt="User avatar">
                                <p>
                                    {{ user }}
                                    <small>Member since {{ user.date_joined|naturalday }}</small>
                                </p>
                            </li>
                            <li class="user-footer">
                                <div class="pull-left">
                                    <a href="{% url 'users:profile' %}" class="btn btn-default btn-flat">
                                        <i class="fa fa-user margin-right-sm"></i>Profile
                                    </a>
                                </div>
                                <div class="pull-right">
                                    <a href="{% url 'django.contrib.auth.views.logout' %}" class="btn btn-default btn-flat">
                                        <i class="fa fa-sign-out margin-right-sm"></i>Sign out
                                    </a>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            {% endif %}
        </div>
    </nav>
</header>

fh/templates/partials/navbar.html
{% load staticfiles %}
{% load sitetree %}
{% load avatar_tags %}

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'index' %}">
                <img id="fh-navbar-logo" src="{% static 'img/favicon_24x24.png' %}" height="24" width="24">
                <span class="hidden-sm margin-left-md">FamilyHelper</span>
            </a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">

            {% sitetree_menu from 'navbar' include "trunk" template "sitetree/menu_bootstrap3.html" %}

            {% if user.is_authenticated %}
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a id="fh-navbar-avatar-link" href="{% url 'users:profile' %}"
                           data-toggle="tooltip" title="Your profile page" data-placement="bottom">
                            <img src="{% cached_avatar_url user 24 %}" id="fh-navbar-avatar">
                            <span class="hidden-sm margin-left-md">{{ user|default:user }}</span>
                        </a>
                    </li>
                    <li><a href="{% url 'django.contrib.auth.views.logout' %}"><i class="fa fa-sign-out"></i> Log
                        out</a></li>
                </ul>
            {% endif %}
        </div>
    </div>
</nav>

fh/templates/partials/sidebar.html
{% load sitetree %}

<aside class="main-sidebar">
    <section class="sidebar">
        {% sitetree_menu from 'navbar' include "trunk" template "sitetree/menu_bootstrap3.html" %}
    </section>
</aside>

fh/templates/partials/thead.html
{% load url_replace %}

<thead>
<tr>
    {% for th in thead %}
        <th class="{{ th.class }}">
            {% if th.sort %}
                {% if request.GET.sort == th.sort %}
                    <small>
                        <i class="fa fa-sort-amount-{{ request.GET.order }} margin-right-sm"></i>
                    </small>
                {% endif %}
                {% if request.GET.order == 'asc' and request.GET.sort == th.sort %}
                    <a href="{% url link %}?{% url_replace request sort=th.sort order='desc' %}">
                {% else %}
                    <a href="{% url link %}?{% url_replace request sort=th.sort order='asc' %}">
                {% endif %}
            {{ th.title|title }}
            </a>

            {% else %}
                {{ th.title|title }}
            {% endif %}
        </th>
    {% endfor %}
    <th class="td-sm text-right"></th>
</tr>
</thead>