fh/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from ratelimitbackend import admin
from django.views.generic.base import RedirectView
from users.views import PasswordChangeRedirectView
from users.forms import ValidatingPasswordChangeForm
from fh.views import tags

admin.autodiscover()

admin.site.site_header = 'FamilyHelper administration'

urlpatterns = [
    url(r'^autocomplete/', include('autocomplete_light.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', auth_views.login, name='login'),
    url(r'^accounts/logout', auth_views.logout, {'next_page': '/'}),
    url(r'tags/$', tags, name='tags_all'),
    url(r'tags/(?P<query>.+)/$', tags, name='tags_query'),
    url(r'^finances/', include('finances.urls', namespace="finances")),
    url(r'^tasks/', include('tasks.urls', namespace="tasks")),
    url(r'^tv/', include('tv.urls', namespace="tv")),
    url(r'^analytics/', include('analytics.urls', namespace="analytics")),
    url(r'users/profile/password$', auth_views.password_change, {
        'template_name': 'users/password_change_form.html', 'password_change_form': ValidatingPasswordChangeForm},
        name='password_change'),
    url(r'users/profile/password/done$', PasswordChangeRedirectView.as_view(), name='password_change_done'),
    url(r'^users/', include('users.urls', namespace="users")),
    url(r'^avatar/', include('avatar.urls')),
    url(r'^$', RedirectView.as_view(pattern_name='finances:payments_list', permanent=True), name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf.urls import url
import users.views as views


urlpatterns = [
    url(r'profile$', views.Profile.as_view(), name='profile'),
    url(r'profile/edit$', views.UserUpdate.as_view(), name='profile_edit'),
]

users/models.py
from django.contrib.auth.models import User as BaseUser


class User(BaseUser):
    class Meta:
        proxy = True

    def __str__(self):

        if self.first_name:
            return '%s %s' % (self.last_name, self.first_name)
        else:
            return '%s' % self.username

users/forms.py
from django import forms
from django.contrib.auth.forms import PasswordChangeForm


class ValidatingPasswordChangeForm(PasswordChangeForm):
    MIN_LENGTH = 6

    def clean_new_password1(self):
        password1 = self.cleaned_data.get('new_password1')

        # At least MIN_LENGTH long
        if len(password1) < self.MIN_LENGTH:
            raise forms.ValidationError("The new password must be at least %d characters long." % self.MIN_LENGTH)

        # At least one letter and one non-letter
        first_isalpha = password1[0].isalpha()
        if all(c.isalpha() == first_isalpha for c in password1):
            raise forms.ValidationError("The new password must contain at least one letter and at least one digit or" \
                                        " punctuation character.")

        return password1

users/views.py
from django.views.generic import TemplateView, UpdateView, RedirectView
from django.contrib.messages.views import SuccessMessageMixin
from finances.models import Payment
from django.db.models import Avg
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse_lazy
from django.contrib import messages


class PasswordChangeRedirectView(RedirectView):
    """
    Password change done redirect
    """
    permanent = False
    url = reverse_lazy('users:profile')

    def get_redirect_url(self, *args, **kwargs):
        messages.success(self.request, 'Password was updated successfully.')

        return super(PasswordChangeRedirectView, self).get_redirect_url(*args, **kwargs)


class Profile(TemplateView):
    """
    Profile view
    """

    template_name = 'users/profile.html'

    def get_context_data(self, **kwargs):
        context = super(Profile, self).get_context_data(**kwargs)
        context['payments_total'] = Payment.objects.filter(created_by=self.request.user).count()
        context['average_payment'] = round(
            list(Payment.objects.filter(created_by=self.request.user).filter(is_incoming=False).aggregate(
                Avg('amount')).values())[0], 2)

        return context


class UserUpdate(SuccessMessageMixin, UpdateView):
    """
    User update view
    """
    model = User
    fields = ['last_name', 'first_name', 'email']
    success_url = reverse_lazy('users:profile')
    success_message = "Profile was updated successfully"
    template_name = 'users/profile_edit.html'

    def get_object(self):
        return self.request.user

users/templates/users/layout.html
{% extends 'layout.html' %}

users/templates/users/password_change_form.html
{% extends 'users/profile_layout.html' %}
{% load crispy_forms_tags %}

{% block tabs %}
    {% with 'security' as tab %}{{ block.super }}{% endwith %}
{% endblock tabs %}

{% block profile_content %}

    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form|crispy }}

        <button type="submit" class="btn btn-success margin-right-sm">
            <i class="fa fa-check-circle-o"></i><span class="margin-left-sm">Update password</span>
        </button>
        <a href="{% url 'users:profile' %}" class="btn btn-default">
            <i class="fa fa-ban"></i><span class="hidden-xs margin-left-sm">Cancel</span>
        </a>
    </form>

{% endblock %}

users/templates/users/profile.html
{% extends 'users/profile_layout.html' %}
{% load humanize %}

{% block profile_content %}

    <table class="table table-striped table-hover">
        <tbody>
        <tr>
            <th class="td-sm-md"><strong>Username:</strong></th>
            <td>{{ user.username }}</td>
        </tr>
        <tr>
            <th class="td-sm-md"><strong>Last name:</strong></th>
            <td>{{ user.last_name|default:'none' }}</td>
        </tr>
        <tr>
            <th class="td-sm-md"><strong>First name:</strong></th>
            <td>{{ user.first_name|default:'none' }}</td>
        </tr>
        <tr>
            <th class="td-sm-md"><strong>E-mail:</strong></th>
            <td>{{ user.email|default:'none' }}</td>
        </tr>
        <tr>
            <th class="td-sm-md"><strong>Total payments:</strong></th>
            <td>{{ payments_total|intcomma }}</td>
        </tr>
        <tr>
            <th class="td-sm-md"><strong>Average payment:</strong></th>
            <td>{{ average_payment|intcomma }}</td>
        </tr>
        </tbody>
    </table>
    <a href="{% url 'users:profile_edit' %}" class="btn btn-success">
        <i class="fa fa fa-pencil-square-o margin-right-sm"></i>Edit profile
    </a>
{% endblock %}

users/templates/users/profile_edit.html
{% extends 'users/profile_layout.html' %}
{% load crispy_forms_tags %}

{% block profile_content %}

    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form|crispy }}

        <button type="submit" class="btn btn-success margin-right-sm">
            <i class="fa fa-check-circle-o"></i><span class="margin-left-sm">Update profile</span>
        </button>
        <a href="{% url 'users:profile' %}" class="btn btn-default">
            <i class="fa fa-ban"></i><span class="hidden-xs margin-left-sm">Cancel</span>
        </a>
    </form>
{% endblock %}

users/templates/users/profile_layout.html
{% extends 'users/layout.html' %}
{% load humanize %}
{% load avatar_tags %}
{% load staticfiles %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'users/css/profile.css' %}">
{% endblock %}

{% block content %}

    <div class="nav-tabs-custom">
        {% block tabs %}
            <ul class="nav nav-tabs" role="tablist">
                <li role="presentation" {% if tab == 'profile' or not tab %}class="active"{% endif %}>
                    <a href="{% url 'users:profile' %}" aria-controls="home" role="tab">
                        <i class="fa fa-user"></i> {{ user.username|capfirst }}`s profile
                    </a>
                </li>
                <li role="presentation" {% if tab == 'security' %}class="active"{% endif %}>
                    <a href="{% url 'password_change' %}" aria-controls="security">
                        <i class="fa fa-lock"></i> Security
                    </a>
                </li>
                <li role="presentation" {% if tab == 'avatars' %}class="active"{% endif %}>
                    <a href="{% url 'avatar_change' %}" aria-controls="avatars">
                        <i class="fa fa-camera"></i> Avatars
                    </a>
                </li>
            </ul>
        {% endblock %}

        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active margin-top-md-lg">
                    <div class="col-sm-3" id="profile-avatar-col">
                        <a href="{% url 'avatar_change' %}" data-toggle="tooltip" title="Change your avatar"
                           data-placement="bottom">
                            <img src="{% avatar_url user 250 %}" class="img-responsive img-rounded hidden-xs">
                        </a>
                    </div>
                    <div class="col-sm-9">
                        {% block profile_content %}{% endblock %}
                    </div>
            </div>
        </div>
    </div>
{% endblock %}