fh/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from ratelimitbackend import admin
from django.views.generic.base import RedirectView
from users.views import PasswordChangeRedirectView
from users.forms import ValidatingPasswordChangeForm
from fh.views import tags

admin.autodiscover()

admin.site.site_header = 'FamilyHelper administration'

urlpatterns = [
    url(r'^autocomplete/', include('autocomplete_light.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', auth_views.login, name='login'),
    url(r'^accounts/logout', auth_views.logout, {'next_page': '/'}),
    url(r'tags/$', tags, name='tags_all'),
    url(r'tags/(?P<query>.+)/$', tags, name='tags_query'),
    url(r'^finances/', include('finances.urls', namespace="finances")),
    url(r'^tasks/', include('tasks.urls', namespace="tasks")),
    url(r'^tv/', include('tv.urls', namespace="tv")),
    url(r'^analytics/', include('analytics.urls', namespace="analytics")),
    url(r'users/profile/password$', auth_views.password_change, {
        'template_name': 'users/password_change_form.html', 'password_change_form': ValidatingPasswordChangeForm},
        name='password_change'),
    url(r'users/profile/password/done$', PasswordChangeRedirectView.as_view(), name='password_change_done'),
    url(r'^users/', include('users.urls', namespace="users")),
    url(r'^avatar/', include('avatar.urls')),
    url(r'^$', RedirectView.as_view(pattern_name='finances:payments_list', permanent=True), name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tv/urls.py
from django.conf.urls import url

import tv.views as views

urlpatterns = [
    url(r'channel/$', views.ChannelList.as_view(), name='channels_list'),
    url(r'channel/(?P<pk>[0-9]+)/$', views.ChannelShow.as_view(), name='channel_show'),
]

tv/models.py
from django.db import models
from fh.models import CommonInfo
from django.core.urlresolvers import reverse


class Channel(CommonInfo):
    """ Channel model """

    CATEGORIES = {
        'Kids': 'fa fa-child',
        'Educational': 'fa fa-flask',
        'Public': 'fa fa-group',
        'Music': 'fa fa-music',
        'Sport': 'fa fa-futbol-o',
        'Regional': 'fa fa-globe',
        'Entertainment': 'fa fa-star',
        'Man': 'fa fa-male',
        'Woman': 'fa fa-female',
        'Films': 'fa fa-film',
        'News': 'fa fa-newspaper-o',
        'Religion': 'fa fa-bolt',
        'Other': 'fa fa-tv'
    }

    title = models.CharField(max_length=255)
    category = models.CharField(max_length=255, choices=[(i, i) for i in sorted(CATEGORIES.keys())])
    is_enabled = models.BooleanField(default=True, verbose_name='Is enabled?')
    code = models.TextField()
    alternative_code = models.TextField(null=True, blank=True)
    is_favorite = models.BooleanField(default=False, verbose_name='Is favorite?')

    def get_absolute_url(self):
        return reverse('tv:channel_show', kwargs={'pk': self.pk})

    def __str__(self):
        return '%s' % self.title

    class Meta:
        ordering = ['category', 'title']

tv/forms.py
from django import forms

# place form definition here

tv/views.py
from collections import OrderedDict
from django.views.generic import ListView, DetailView, UpdateView
from tv.models import Channel


class ChannelList(ListView):
    """
    Channels list
    """
    model = Channel

    def get_context_data(self, **kwargs):
        context = super(ChannelList, self).get_context_data(**kwargs)
        channels = OrderedDict()
        for channel in context['object_list']:
            if channel.category not in channels:
                channels[channel.category] = []
            channels[channel.category].append(channel)
        context['channels'] = channels
        context['icons'] = Channel.CATEGORIES
        return context

    def get_queryset(self):
        return Channel.objects.all().filter(is_enabled=True)


class ChannelShow(UpdateView):
    """
    Channel show
    """
    model = Channel
    fields = ['is_favorite']

tv/templates/tv/channel_form.html
{% extends 'tv/layout.html' %}
{% load crispy_forms_tags %}

{% block tv_content %}
    {% if channel.alternative_code %}
    <h3>Main player</h3>
    {% endif %}
    {{ channel.code|safe }}
    {% if channel.alternative_code %}
        <h3>Alternative player</h3>
        {{ channel.alternative_code|safe }}
    {% endif %}

    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form|crispy }}

        <button type="submit" class="btn btn-success margin-right-sm">
            <i class="fa fa-check-circle-o"></i><span class="margin-left-sm">Save channel</span>
        </button>
        <a href="{% url 'tv:channels_list' %}" class="btn btn-default">
            <i class="fa fa-ban"></i><span class="hidden-xs margin-left-sm">Cancel</span>
        </a>
    </form>

{% endblock %}

tv/templates/tv/channel_list.html
{% extends 'tv/layout.html' %}
{% load main %}
{% block tv_content %}

    {% if object_list|length %}
        {% for category in channels %}
            <div class="channels-category">
                <h4>
                    {% if icons|get_item:category %}
                        <i class="{{ icons|get_item:category }}"></i>
                    {% else %}
                        <i class="fa fa-circle-o"></i>
                    {% endif %}
                    {{ category }}
                </h4>
                <ul>
                    {% for channel in channels|get_item:category %}
                        <li class="{{ channel.is_favorite|yesno:"favorite-channel," }}"><a href="{% url 'tv:channel_show' channel.id %}">{{ channel }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        {% endfor %}

    {% else %}
        <div class="alert alert-warning">
            <i class="fa fa-exclamation-circle"></i> Channels not found.
        </div>
    {% endif %}

{% endblock %}

tv/templates/tv/layout.html
{% extends 'layout.html' %}
{% load staticfiles %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'tv/css/channels.css' %}">
{% endblock %}

{% block content %}
    <div class="box box-default">
        <div class="box-body">
            {% block tv_content %}{{ block.super }}{% endblock %}
        </div>
    </div>
{% endblock %}